# Generated by Django 5.2.4 on 2025-07-16 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraping_data', '0002_swaggerproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date du test')),
                ('method', models.CharField(max_length=10)),
                ('url', models.URLField(max_length=2000)),
                ('status_code', models.IntegerField()),
                ('response_body', models.TextField(blank=True, null=True)),
                ('test_status', models.CharField(help_text="Ex: 'passed' ou 'failed'", max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='scraping_data.swaggerproject')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
